simplemooc_backend/core/urls.py
from django.conf.urls import url, patterns


urlpatterns = patterns('simplemooc_backend.core.views',
                       url(r'^$', 'home', name='home'),
                       url(r'^core/$', 'contact', name='contact'),
                       )

simplemooc_backend/courses/urls.py
from django.conf.urls import url, patterns, include


urlpatterns = patterns('simplemooc_backend.courses.views',
                       url(r'^$', 'index', name='index'),
                       # url(r'^(?P<pk>\d+)/$', 'details', name='details'),
                       url(r'^(?P<slug>[\w_-]+)/$', 'details', name='details'),
                       )

simplemooc_backend/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    url(r'^', include('simplemooc_backend.core.urls', namespace='core')),
    url(r'^courses/', include('simplemooc_backend.courses.urls', namespace='courses')),
    url(r'^admin/', include(admin.site.urls)),
]

"""
 Isso server apenas para ambiente de desenvolvimento aonde é necessário apontar o local dos arquivos estáticos.
 Pois o django em modo debug não server os arquivos. 
 Em servidores de produção é utilizado um servidor a parte para os arquivos estáticos.
"""
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

simplemooc_backend/core/models.py
from django.db import models

# Create your models here.

simplemooc_backend/courses/models.py
from django.db import models


class CourseManager(models.Manager):

    def search(self, query):
        self.get_queryset().filter(
            models.Q(name__icontains=query) |
            models.Q(description__icontains=query))


class Course(models.Model):

    name = models.CharField('Nome', max_length=100)

    slug = models.SlugField('Atalho', unique=True)

    description = models.TextField('Descrição Simples', blank=True)

    about = models.TextField('Sobre o Curso', blank=True)

    start_date = models.DateField('Data de Ínicio', null=True, blank=True)

    image = models.ImageField(
        upload_to='courses/images',
        verbose_name='Imagem',
        null=True, blank=True
    )

    created_at = models.DateTimeField(
        'Criado em', auto_now_add=True
    )

    updated_at = models.DateTimeField(
        'Atualizado em', auto_now=True
    )

    object = CourseManager()

    class Meta:
        verbose_name = "Curso"
        verbose_name_plural = "Cursos"
        ordering = ['-created_at']

    def __str__(self):
        return "{}".format(self.name)

    @models.permalink
    def get_absolute_url(self):
        return 'courses:details', (), {'slug': self.slug}

simplemooc_backend/core/views.py
from django.shortcuts import render
from django.http import HttpResponse


def home(request):
    return render(request, 'home.html', {})

def contact(request):
    return render(request, 'contact.html', {})

simplemooc_backend/courses/views.py
from django.shortcuts import render, get_object_or_404
from .models import Course


def index(request):
    return render(request, "courses/index.html", {"courses": Course.object.all()})


def details(request, slug):
    course = get_object_or_404(Course, slug=slug)
    context = {
        'course': course
    }
    template_name = 'courses/details.html'
    return render(request, template_name, context)

simplemooc_backend/core/templates/base.html
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Simple MOOC - Uma simples plataforma de ensino a distância" />
    <title>Simple MOOC</title>
    <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.3.0/pure-min.css">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
</head>
<div class="header">
    <div class="pure-menu pure-menu-open pure-menu-fixed pure-menu-horizontal">
        <a class="pure-menu-heading" href="">SIMPLE MOOC</a>
        <ul>
            <li class="pure-menu-selected"><a href="{% url 'core:home' %}">Início</a></li>
            <li><a href="{% url 'courses:index' %}">Cursos</a></li>
            <li><a href="{% url 'core:contact' %}">Contato</a></li>
            <li><a href="#">Sobre</a></li>
            <li><a href="#">DarkMode</a></li>
        </ul>
    </div>
</div>
<body>
{% block content %}
{% endblock %}
</body>
<div class="footer">
    Simple MOOC - Uma simples plataforma de ensino a distância
</div>
<script src="http://yui.yahooapis.com/3.12.0/build/yui/yui-min.js"></script>

simplemooc_backend/core/templates/contact.html
{% extends "base.html" %}
{% block content %}
    <div class="content">
    <div class="pure-g-r content-ribbon">
        <div class="pure-u-1">
            <h1>Fale conosco</h1>
            <p>Você pode entrar em contato conosco tanto por e-mail como pelas redes sociais, abaixo seguem os links para contato:</p>
            <h4>Links</h4>
            <ul>
                <li>E-mail: <a href="mailto:contato@simplemooc.org">contato@simplemooc.org</a></li>
                <li>Twitter: <a href="https://twitter.com/simplemooc">@simplemooc</a></li>
            </ul>
        </div>
    </div>
</div>
{% endblock %}

simplemooc_backend/core/templates/home.html
{% extends "base.html" %}
{% block content %}
    <div class="content">
        <div class="splash">
            <div class="pure-g-r">
                <div class="pure-u-1">
                    <div class="l-box splash-text">
                        <h1 class="splash-head">
                            Uma Simples Plataforma de Ensino a Distância
                        </h1>
                        <h2 class="splash-subhead">
                            O Simple MOOC visa simplificar o ensino a distância, provendo ferramentas objetivas e de fácil uso para cursos a distância.
                        </h2>
                        <p>
                            <a href="#" class="pure-button primary-button">Saiba mais</a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
        <div class="content">
            <div class="pure-g-r content-ribbon">
                <div class="pure-u-2-3">
                    <div class="l-box">
                        <h4 class="content-subhead">Vídeo-aulas e materiais digitais</h4>
                        <h3>Publique suas aulas</h3>
                        <p>
                            O Simple MOOC tem um sistema simples e prático para que o professor disponibilize vídeo-aulas e materiais digitais como: pdf's, slides, imagens ...
                        </p>
                    </div>
                </div>
                <div class="pure-u-1-3">
                    <div class="l-box">
                        <img src="http://placehold.it/400x250"
                             alt="Vídeo aulas e materiais digitais.">
                    </div>
                </div>
            </div>
            <div class="pure-g-r content-ribbon">
                <div class="pure-u-1-3">
                    <div class="l-box">
                        <img src="http://placehold.it/400x250"
                             alt="Fórum de Dúvidas">
                    </div>
                </div>
                <div class="pure-u-2-3">
                    <div class="l-box">
                        <h4 class="content-subhead">Fórum de Dúvidas</h4>
                        <h3>Interaja com seus Alunos</h3>
                        <p>
                            No Simple MOOC você pode ter seu próprio sistema de fórum para que seus alunos possam interagir com você e com os outros alunos
                        </p>
                    </div>
                </div>
            </div>
            <div class="pure-g-r content-ribbon">
                <div class="pure-u-2-3">
                    <div class="l-box">
                        <h4 class="content-subhead">Exercícios</h4>
                        <h3>Crie exercícios para avaliar seus alunos</h3>
                        <p>
                            Você pode criar exercícios para que os alunos possam ser avaliados e todo o controle de notas e resolução dos exercícios é controlado pela plataforma, facilitando sua vida
                        </p>
                    </div>
                </div>
                <div class="pure-u-1-3">
                    <div class="l-box">
                        <img src="http://placehold.it/400x250"
                             alt="Exercícios">
                    </div>
                </div>
            </div>
            <div class="pure-g-r content-ribbon">
                <div class="pure-u-1-3">
                    <div class="l-box">
                        <img src="http://placehold.it/400x250"
                             alt="Mural de Avisos">
                    </div>
                </div>
                <div class="pure-u-2-3">
                    <div class="l-box">
                        <h4 class="content-subhead">Mural de Avisos</h4>
                        <h3>Envie anúncios diretamente para os alunos</h3>
                        <p>
                            Organize os avisos do seu curso de forma fácil e simples.
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

simplemooc_backend/courses/templates/courses/details.html
{% extends "base.html" %}

{% load static %}

{% block content %}
<div class="splash">
    <div class="pure-g-r">
        <div class="pure-u-1">
            <div class="l-box splash-text">
                <h1 class="splash-head">
                    {{ course.name }}
                </h1>
                <h2 class="splash-subhead">
                    {{ course.description }}
                </h2>
                <p>
                    <a href="#" class="pure-button primary-button">Inscreva-se</a>
                </p>
            </div>
        </div>
    </div>
</div>
<div class="pure-g-r content-ribbon">
    <div class="pure-u-2-3">
        <div class="l-box">
            <h4 class="content-subhead">Sobre o Curso</h4>
            {{ course.about|linebreaks }}
        </div>
    </div>
    <div class="pure-u-1-3">
        <div class="l-box">
            {% if course.image %}
            <img src="{{ course.image.url }}" alt="" />
            {% else %}
            <img src="{% static 'img/course.png' %}" alt="" />
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

simplemooc_backend/courses/templates/courses/index.html
{% extends "base.html" %}

{% load static %}

{% block content %}
<div class="content">
    <div class="pure-g-r content-ribbon">
        <div class="pure-u-1">
            <div class="l-box">
                <h4 class="content-subhead">Listagem de Cursos do SimpleMOOC</h4>
                <p>Abaixo a lista de cursos disponíveis na plataforma</p>
            </div>
        </div>
    </div>
    {% for course in courses %}
    <div class="pure-g-r content-ribbon">
        <div class="pure-u-1-3">
            <div class="l-box">
                <a href="{{ course.get_absolute_url }}">
                    {% if course.image %}
                        <img src="{{ course.image.url }}" alt="{{ course.name }}" />
                    {% else %}
                        <img src="{% static 'img/course.png' %}" alt="" />
                    {% endif %}
                </a>
            </div>
        </div>
        <div class="pure-u-2-3">
            <div class="l-box">
                <h4 class="content-subhead"><a href="{{ course.get_absolute_url }}" title="">{{ course.name }}</a></h4>
                {{ course.description|linebreaks }}
            </div>
        </div>
    </div>
    {% empty %}
        <div class="pure-g-r content-ribbon">
            <div class="pure-u-1">
                <div class="l-box">
                    <p>Nenhum curso está disponível na plataforma</p>
                </div>
            </div>
        </div>
    {% endfor %}
{% endblock %}